
syntax = "proto3";

package file;

service FileService{
  rpc UploadFile(stream FileChunk) returns (UploadResponse);
  rpc SearchFile(SearchRequest) returns (SearchResponse);
}

message FileInfo {
  string file_name = 1;
  int64 file_size_bytes = 2;
}

message SearchRequest{
  string file_name = 1;
}

message SearchResponse{
  repeated FileInfo files = 1;
  int32 total_found = 2;
}

message FileChunk{
  string filename = 1;
  bytes data = 2;
  uint64 offset = 3;
  bool is_last = 4;
  string path = 5;
}

message UploadResponse{
  string file_id = 1;
  string status = 2;
  string message = 3;
}

