CREATE TABLE IF NOT EXISTS vnodes (
  server_address TEXT NOT NULL,
  discovered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
